CREATE TABLE region
(
  R_REGIONKEY BIGINT ENCODE RAW,
  R_NAME CHAR(256) ENCODE RAW,
  R_COMMENT VARCHAR(256) ENCODE RAW
);

CREATE TABLE nation
(
  N_NATIONKEY BIGINT ENCODE RAW,
  N_NAME CHAR(256) ENCODE RAW,
  N_REGIONKEY BIGINT ENCODE RAW,
  N_COMMENT VARCHAR(256) ENCODE RAW
);

CREATE TABLE part
(
  P_PARTKEY BIGINT ENCODE RAW,
  P_NAME CHAR(256) ENCODE RAW,
  P_MFGR CHAR(256) ENCODE RAW,
  P_BRAND CHAR(256) ENCODE RAW,
  P_TYPE CHAR(256) ENCODE RAW,
  P_SIZE INTEGER ENCODE RAW,
  P_CONTAINER CHAR(256) ENCODE RAW,
  P_RETAILPRICE NUMERIC(12, 2) ENCODE RAW,
  P_COMMENT CHAR(256) ENCODE RAW
);

CREATE TABLE supplier
(
  S_SUPPKEY BIGINT ENCODE RAW,
  S_NAME CHAR(256) ENCODE RAW,
  S_ADDRESS CHAR(256) ENCODE RAW,
  S_NATIONKEY BIGINT ENCODE RAW,
  S_PHONE CHAR(256) ENCODE RAW,
  S_ACCTBAL NUMERIC(12, 2) ENCODE RAW,
  S_COMMENT CHAR(256) ENCODE RAW
);

CREATE TABLE customer
(
  C_CUSTKEY BIGINT ENCODE RAW,
  C_NAME VARCHAR(256) ENCODE RAW,
  C_ADDRESS VARCHAR(256) ENCODE RAW,
  C_NATIONKEY BIGINT ENCODE RAW,
  C_PHONE CHAR(256) ENCODE RAW,
  C_ACCTBAL NUMERIC(12, 2) ENCODE RAW,
  C_MKTSEGMENT CHAR(256) ENCODE RAW,
  C_COMMENT VARCHAR(256) ENCODE RAW
);

CREATE TABLE partsupp
(
  PS_PARTKEY BIGINT ENCODE RAW,
  PS_SUPPKEY BIGINT ENCODE RAW,
  PS_AVAILQTY INTEGER ENCODE RAW,
  PS_SUPPLYCOST NUMERIC(12, 2) ENCODE RAW,
  PS_COMMENT CHAR(256) ENCODE RAW
);

CREATE TABLE orders
(
  o_orderkey BIGINT DISTKEY ENCODE RAW,
  o_custkey BIGINT ENCODE RAW,
  o_orderstatus CHAR(256) ENCODE RAW,
  o_totalprice NUMERIC(12, 2) ENCODE RAW,
  o_orderdate CHAR(10) ENCODE RAW,
  o_orderpriority CHAR(256) ENCODE RAW,
  o_clerk CHAR(256) ENCODE RAW,
  o_shippriority INTEGER ENCODE RAW,
  o_comment VARCHAR(256) ENCODE RAW
);

CREATE TABLE lineitem
(
  l_orderkey BIGINT DISTKEY ENCODE RAW,
  l_partkey BIGINT ENCODE RAW,
  l_suppkey INTEGER ENCODE RAW,
  l_linenumber INTEGER ENCODE RAW,
  l_quantity NUMERIC(12, 2) ENCODE RAW,
  l_extendedprice NUMERIC(12, 2) ENCODE RAW,
  l_discount NUMERIC(12, 2) ENCODE RAW,
  l_tax NUMERIC(12, 2) ENCODE RAW,
  l_returnflag CHAR(256) ENCODE RAW,
  l_linestatus CHAR(256) ENCODE RAW,
  l_shipdate CHAR(10) ENCODE RAW,
  l_commitdate CHAR(10) ENCODE RAW,
  l_receiptdate CHAR(10) ENCODE RAW,
  l_shipinstruct CHAR(256) ENCODE RAW,
  l_shipmode CHAR(256) ENCODE RAW,
  l_comment VARCHAR(256) ENCODE RAW
);
